[package]
name = "elkrs-layered"
version = "1.0.0"
publish = false
description = "Initial clean-room ELK Layered layout implementation for elkrs"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
elkrs-core = { version = "1.0.0", path = "../elkrs-core" }

[dev-dependencies]
elkrs-json = { version = "1.0.0", path = "../elkrs-json" }
